### ISSUE TITLE
[Campaign Dir] Change `wesnoth-deception` repo name to just "

### ISSUE THREAD

**Issue by knyghtmare** [schilffarth/wesnoth-deception#2]
Since they still refuse to allow AI Art for wesnoth in general, I have to download the github zip or clone it, but when I do I

**Comment by schilffarth** [comment]
I assume you wanted it to be renamed to just "deception". Did that. Thank you :) Also, Part 1 is finished since today, with easy and normal difficulties play tested by myself. I seek a lot of balancing feedback though, because I believe the more opinionated difficulty balances I implement, the better the overall result will be. 

Expert difficulty isn't play tested by myself, because I do not consider myself even close to a good wesnoth player.
