### ISSUE TITLE
Feedback Report from Wesnoth UMC Discord server

### ISSUE THREAD

**Issue by knyghtmare** [schilffarth/wesnoth-deception#4]
Scenario 1:
***
- Noticed that the higher levels of Kalgor do not have team coloring magenta shades. Might be fixed in later versions since I saw a graphics update commit.
- I like the story telling style of this campaign.
- A lot of the introductory scenario character names: (Kargul/Kalgor/Urgok) seem to be matching characters found in World of Warcraft.
- First scenario is okay. I found a tactic to keep most of my units alive. Was not optimal to do that in the challenging difficulty though.

Scenario 2:
***
- The map could use some more quality improvements. Looks rather bland/plain.
- When i killed a second enemy leader, I got the message "the third chieftain fell..". I think it should be "the second". Might be a typo/bug here.

Scenario 3:
***
- scenario events pop maybe too quickly. I think I am better off not following the first objective and going for the second and third ones
- troll allies did nothing useful except be fodder. Might be worth if they could be strengthened.
- trolls got bulldozed on flat terrain in daytime.

Scenario 4:
***
- scenario is okay. I think the item buffs for Kalgor are a bit underperforming.
- I noticed the way of strength AMLA option seems very underperforming compared to endurance (+1 damage seems quite insignificant compared to +20 HP). The leadership AMLA is rather at value 0 since all I get is level 3 units recalled.

Scenario 5:
***
- This was more story heavy so nothing much to say. No error messages
- I had this issue with the object items being stacked on Kalgor weirdly. Melee weapons placed infront of ranged weapons, and ranged attack "ring of darkness" being rather decreasing in damage output per level. Might be playing an older version, so no clue if this has been addressed already.

Scenario 6
***
- Easy scenario. Undead at night time with orcs bulldozed the undead. I was on Story mode so might be why it felt so easy
- I see the benefit of the leadership AMLA now...but I got it the very last moment so it was not really that useful.

Scenario 7:
***
- I got a question. Is Voldur some orc-elf necromancer? Voldur means "orc-elf hybrid" (googled it).

### Summary
***
I think this is good campaign with refined storytelling, and it's a shame that such a good piece isn't allowed on the addon server. It should be.
Nice to see a campaign utilising AI Art technology to generate portraits and story slides. It really points out the extent to which one augment add-on quality if AI-artwork is allowed for Add-ons.

BTW, if you want an invite to the Wesnoth UMC discord, let me know.

**Comment by schilffarth** [comment]
Yeah, a shame this isn't allowed on the add-on server... :(

Thank you very much for the detailed feedback. I will answer all of your pointed out issues / suggestions the next 2 days, for now too busy irl.

I would greatly appreciate an invite to the Wesnoth UMC discord :)

**Comment by schilffarth** [comment]
Scenario 1:

_Noticed that the higher levels of Kalgor do not have team coloring magenta shades. Might be fixed in later versions since I saw a graphics update commit._
**=> I have already finished sprites for levels 1 - 4 of a base orc unit, which I called "Orcish Brawler", "Orcish Brutestalker", "Orcish Bloodscourge" and "Orcish Doombringer". These units will be used as base units for Kalgor in Part 1 and Durok in Part 2. For Kalgor in Part 2, I am planning on creating kind of "corrupted orc" sprites. These sprites / base units haven't been implemented for Kalgor yet though, only for Durok in Part 2 (of which scenarios 1, 2 and 3a, the elve's storyline are playable now iirc)**

_A lot of the introductory scenario character names: (Kargul/Kalgor/Urgok) seem to be matching characters found in World of Warcraft._
**Woops. Well, should I change it? lol**

_First scenario is okay. I found a tactic to keep most of my units alive. Was not optimal to do that in the challenging difficulty though._
**Generally speaking, with Storymode / Easy difficulty I aimed at those who don't really know how to play the game. Basically this very simple mode should make the player win with a high chance even if they just brain-deadly rush their units into the enemy, no matter villages, daytime or other strategic concerns. Normal mode was balanced to fit my own playstyle, as I consider myself a mediocre Wesnoth-player. Hard difficulty was simply set a tad more difficult than Normal mode, but I myself wouldn't be able to complete it on Hard. Lol.**

Scenario 2:

_The map could use some more quality improvements. Looks rather bland/plain._
**I will wok on that idea. I have already had the idea of adding another village to the east of the northern river bridge, as well as some forest spread around the map. Maybe some unevenness, idk.**

_When i killed a second enemy leader, I got the message "the third chieftain fell..". I think it should be "the second". Might be a typo/bug here._
**It was originally planned to make the player kill 3 leaders, not just 2. But I tuned it later on throughout development, so I will have to adjust this message. Thank you for pointing it out.**

Scenario 3:

_scenario events pop maybe too quickly. I think I am better off not following the first objective and going for the second and third ones_
**In Normal and Hard difficulties, the seond objective occurs one round later, which should theoretically make it a little more difficult to just camp at your spawn in the east of the map until the escape objectives appear. But I will have to investigate your concern and eventually come up with a solution to improve the overall flow of the scenario.**

_troll allies did nothing useful except be fodder. Might be worth if they could be strengthened._
**That was kinda the only idea I had in mind with them. I will try to come up with something more meaningful. Maybe a troll could accompany Kalgor on his future journey, and the trolls simply join side 1 as the first sightening occurs. Just some thoughs rn.**

_trolls got bulldozed on flat terrain in daytime._
**I will consider adding more unevenness to the northern half of the map, this should fix it.**

Scenario 4:

_scenario is okay. I think the item buffs for Kalgor are a bit underperforming._
**The Ring of Darkness can be made really powerful with 2 successive advancements, i believe it goes up to like 11x4 or 12x4, which is pretty good considering Kalgor's melee strength. Same goes for the Tenebris Touch in Scenario 5, it can be made pretty powerful. As for the Blade of Dread, yeah, it might be underperforming, it deals similar damage to Kalgor's previous simple orcish greatsword attacks. I will consider buffing this.**

_I noticed the way of strength AMLA option seems very underperforming compared to endurance (+1 damage seems quite insignificant compared to +20 HP). The leadership AMLA is rather at value 0 since all I get is level 3 units recalled.
Scenario 5:_
**I will considder buffing it, but I also do not want to revert Kalgor back to his original strength he had in a very early version of my add-on. He was like superb fucking monstrous strong. Especialls with advancements.**

_This was more story heavy so nothing much to say. No error messages_
**Please refer to my comment early in this response, as for difficulty balancing.**

_I had this issue with the object items being stacked on Kalgor weirdly. Melee weapons placed infront of ranged weapons, and ranged attack "ring of darkness" being rather decreasing in damage output per level. Might be playing an older version, so no clue if this has been addressed already._
**What do you mean with object items being stacked weirdly? As for ring of darkness damage, I will have to look into it, maybe it is due to an older version, but i can't say for sure.**

Scenario 6

_Easy scenario. Undead at night time with orcs bulldozed the undead. I was on Story mode so might be why it felt so easy
I see the benefit of the leadership AMLA now...but I got it the very last moment so it was not really that useful._
**IIRC, on normal and hard difficulties, Kalgor takes more damage for resurrecting skeletons. This makes it a much more tactical utility than just "haha spawn them infinitely". Also, Normal mode is very significantly more difficult htan easy mode in this scenario. I would consider scenario 6 the hardest of all in Normal difficulty. But I will look into balancing once more.**

Scenario 7:

_I got a question. Is Voldur some orc-elf necromancer? Voldur means "orc-elf hybrid" (googled it)._
**NGL, I came up with most of the story character names out of my head at some sunday morning, when I decided hey would be cool to turn this into a wesnoth story. But thank you for googling and pointing it out, lol, this is going to allow me an insane story twist for Part 2, or eventually even Part 3. (I have been thinking about making Part 3, which focusses on Voldur.)**

Summary

_I think this is good campaign with refined storytelling, and it's a shame that such a good piece isn't allowed on the addon server. It should be._
**Very sadge, indeed.**

_Nice to see a campaign utilising AI Art technology to generate portraits and story slides. It really points out the extent to which one augment add-on quality if AI-artwork is allowed for Add-ons._
**Yes, I think it has a lot of potential. It truly pushes UMC creation, even for those who suck at art. And art is a major part of Wesnoth add-ons, imo.**

_BTW, if you want an invite to the Wesnoth UMC discord, let me know._
**Sure.**

I will work on the changes this weekend :)

**Comment by knyghtmare** [comment]
> I have already finished sprites for levels 1 - 4 of a base orc unit, which I called "Orcish Brawler", "Orcish Brutestalker", "Orcish Bloodscourge" and "Orcish Doombringer". These units will be used as base units for Kalgor in Part 1 and Durok in Part 2. For Kalgor in Part 2, I am planning on creating kind of "corrupted orc" sprites. These sprites / base units haven't been implemented for Kalgor yet though, only for Durok in Part 2 (of which scenarios 1, 2 and 3a, the elve's storyline are playable now iirc)

You can take a look into Archaic Era's Northern Orcs faction for sprite ideas for the orcs. I like the unit line naming you have. Very reminiscent of World of Warcraft. Doombringer is a raid/dungeon drop I think.

> Woops. Well, should I change it? lol

Not really an issue for me since I used to play WoW religiously back in 2015-2016 and it gave me flashbacks of good memories of being a Horde-player

> NGL, I came up with most of the story character names out of my head at some sunday morning, when I decided hey would be cool to turn this into a wesnoth story. But thank you for googling and pointing it out, lol, this is going to allow me an insane story twist for Part 2, or eventually even Part 3. (I have been thinking about making Part 3, which focusses on Voldur.)

most of the character names if googled, point to WoW (either NPCs or some player characters). I found it amusing actually. [Durok](https://www.wowhead.com/npc=71736/durok) is actually in WoW as an NPC too. Again, not really an issue. It just gave a trip down memory lane. Loktar-Ogar!

> Yes, I think it has a lot of potential. It truly pushes UMC creation, even for those who suck at art. And art is a major part of Wesnoth add-ons, imo.

yes, I was considering AI artwork for my final campaign since having portraits does augment campaign quality by a lot.

> Sure.

Sent. I see you already joined too. Cool

**Comment by schilffarth** [comment]
✅ Implement Orcish Brawler, Brutestalker, Bloodscourge and Doombringer as base units of Kalgor, similar to what I've already done for Durok in Part 2. This fixes the magenta color not changing to team color.
✅ Make the map of scenario 2 more interesting => I added some forest and farm decorations to the flatland, it does at least something, but I am happily hearing suggestions to improve it further.
✅ Update message "As Kalgor fells the third chieftain..." => "... second chieftain..."
✅ Trolls turn side 1 as they are sighted, not just allied
✅ Add more unevenness to the northern half of the map for the third scenario, so trolls aren't slaughtered helplessly on flatland
⏳ Marching west in scenario 3 doesn't make sense strategically once the player knows the successive objectives; the player will just camp the spawn until the signposts appear. Created an individual issue for this: https://github.com/schilffarth/deception/issues/5
✅ Underperforming item buffs => has been buffed in the same commit as I implemented the base unit types brawler etc.
✅ Slightly buffed Way of Strength AMLA
✅ The order of attacks being weird at times should be fixed with the new approach of Kalgor carrying all attacks from the start on, with objects disabling them until their activation

**Comment by schilffarth** [comment]
@knyghtmare I have commited the changes according to my post above. The only thing that's left is the rapid objectives in scenario 3 - I will need time to come up with a good solution, can't think of anything for now. I opened a separate issue for this specifically, so I don't lose it out of sight. Thank you very much once more for the playthrough and great feedback.
